### ISSUE TITLE
Generate SDMs using Saxifragales 12 layer climate data

### ISSUE THREAD

**Issue by cjgrady** [biotaphy/projects#8]
The first set was done with the Worldclim climate dataset but we want to use the 12 layer subset instead

**Comment by cjgrady** [comment]
These are currently running on our old production machine.

**Comment by cjgrady** [comment]
FYI @ryanafolk some of our cluster nodes were having some problems and were not working on the models.  This has slowed it down considerably.  This is probably the last project to use the yeti cluster as we have migrated to new machines for Lifemapper so maintenance on this cluster is minimal.  I was able to restore about 20 additional workers and that has restored a good chunk of concurrency to the computations so they are moving along at a decent pace again (maybe 30,000 a day or so).  I'll try to eke out a bit more so that these computations finish by early next week.

**Comment by ryanafolk** [comment]
Great -- sounds awesome!

**Comment by cjgrady** [comment]
Models are finished and being prepped for the next step

**Comment by ryanafolk** [comment]
Woohoo!!

Ryan A. Folk
Assistant Professor and Herbarium Curator
Department of Biological Sciences
Mississippi State University
295 E. Lee Blvd.
P.O. Box GY
Mississippi State, MS 39762
http://www.ryanafolk.com

On Nov 9, 2021, at 1:17 PM, CJ Grady ***@***.******@***.***>> wrote:



Models are finished and being prepped for the next step

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://secure-web.cisco.com/1cdq382UsXZQ0pzQiCLt8fomVozdliyKrtYrxw_IF8BLMpt6wRDDtt7K-74T0Lpf8OlJjVJJzNz4CcyvmkX1EsD3_lEszdOeFSdndDDHCb8NPhHOJFJb-X5wA3oIAiAw6eDNWmnqqGpgWR7v-PLRBI_d3w9nHlyiMxd7JsUfb2TzLFotiW_JtefDW8sVTgBxrzhjkpQ7S6psMTqSS_JdcilMk_eElL0I4jqUgB_xJJccq_rWcvWzxQPnF8oa3DxKHuLT78N7nLhLUIfZ17TxoNtapVCqpm5OLMGWqXwavqJSGsLovnT4J9RJG6rkDiUbs/https%3A%2F%2Fgithub.com%2Fbiotaphy%2Fprojects%2Fissues%2F8%23issuecomment-964457704>, or unsubscribe<https://secure-web.cisco.com/1Hs8rFcc9JaNTdArNa3lWqOtIWj8SjHpwRXGLQNPM0sRmaMRdEO1JFjvXKNG6SFV1Kbub5tSOCLawstpG1P1ndGoMTjGYzQ2wPsDsOtE7kdK8iTAspzt5jZZGjOvJbpL9a3NK1WOhbtfDPmYWJzdRb-JF2q8Vyo4bX_VCyEjqCyoemjjPBWi6expsH3Az8p-dUqBSnXBp0URGPmvsVxdUZSF24gxuC6VUcEaiOkdxwCNAKlys0QY3Lc41y4TH9g8kbjpwQByLXgyvO0SdDnlQBTJJOj4Fcsaoy_9euw5WfAOfsVmF7ON6wDJGmFjrq6CP/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADT7E7FAUACEGGQ4LEFOHCLULFXTLANCNFSM5G74BC5Q>.
Triage notifications on the go with GitHub Mobile for iOS<https://secure-web.cisco.com/1VXiUyuYc2Fv8BE0HV8gqmw6WnmKLUQVCq4nTp0OKekROk3p4KfLHbvZ1rq5cNZruApYQSVRyuPVvmOcjdIGFWbTk8Y_qpVFdI1fQkGgPBdF1YpxkfXozdrgxVyLRssGQAiCU5t45cLPu1PI8af-MQqmutbkEDGg8YEl2OoKIcRUIDEIqr0SyfBlnR3cAcFYd9w3cqHKF7ia2WrGdrxQYlDy6XMWwa9RMVwjCtXajBKW7HwcSWe9kuY29XP3KS7EynRCCT-jidAktc_uablp0sumEWV7EdIC8RW0QqOJ749P8BSsKL3wqwDxpBIh5cHZs/https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675> or Android<https://secure-web.cisco.com/16k1U8Wgfj_SbT1ZAU80WXp58L_aP2I4DN9JFjXvJXFpFLbky0HLmACDjm6k_QV71obBZgQDVtN5EYX97HfIfG7nI3rW9OQGoggn2Kr0jndwjCovvz8ChWagE_mpHpMOFWyAz5dOvR_EIN5piFAtifSU-jeRDvzcmNHnjCGT01pIkrfMnD0sVgG6K6JG3b8jL4U806qqwPDaqbE7BR8i2wRXKw1MCI5MGuXdjXvPDhenbHkcW1EkOQNSK-1fk7N2tZWDS7V67LcVFlfDbczdFeHVJ1N4KGZX4uoUjm4jyaL919GpOo8MCXNGnx23768Gy/https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub>.

**Comment by cjgrady** [comment]
Reopening this issue.  I have completed models for everything but creating the PAM from them is taking too long.  So, I reset the models with 5 minute data (instead of 2.5 minute) and included the pre- and post- processing steps when they are created.  This will end up speeding up the entire process and I expect that they will finish later this week.
